---
# tasks file for install_apache
- block: # Centos
  - name: Install httpd
    yum: 
      name: httpd
      state: latest

  - name: Start Apache and enable it on the boot
    service: 
      name: httpd
      state: started
      enabled: yes

  - name: Enable port
    firewalld:
      service: http
      permanent: true
      state: enabled
    notify: restart firewalld

  when: ansible_distribution == "CentOS"

- block: # Ubuntu
  - name: Install apache2
    apt:
      name: apache2
      state: latest

  - name: Start Apache and enable it on the boot
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Enable port
    ufw:
      rule: allow
      port: 80
      proto: tcp
    notify: restart ufw

  when:	ansible_distribution == "Ubuntu"

- name: Replace default index file
  template:
    src: index.j2
    dest: "{{ destination }}"
    mode: 0644
  notify:      
    - Restart Apache CentOS
    - restart apache ubuntu
